### ISSUE TITLE
Version 02 Release Request

### ISSUE THREAD

**Issue by BasilGuo** [bemasc/draft-xu-risav#20]
As there are no differences in this draft I think, shall we release the latest version and submit it to [datatracker](https://datatracker.ietf.org/submit/)?
I uploaded the draft manually before, but I don't know whether there is a more convenient way to submit this draft.

**Comment by bemasc** [comment]
OK, I will release tomorrow if there are no more changes requested by then.

**Comment by BasilGuo** [comment]
OK, thanks~
