### ISSUE TITLE
IDEA: Use the AH reserved field instead of RISAV-AH

### ISSUE THREAD

**Issue by bemasc** [bemasc/draft-xu-risav#24]
Instead of allocating a new IP protocol number for RISAV-AH, another option would be change the value in the AH reserved field, which is 16 bits wide and is currently required to be all zeros.  This would allow us to use standard IPsec AH without risking ambiguity with other uses of AH.

This proposal would cost an extra 8 bytes of MTU compared to RISAV-AH, but if the working group is hostile to allocating a new IP protocol number, it could be a useful alternative.

**Comment by BasilGuo** [comment]
[standard AH header format](https://www.rfc-editor.org/rfc/rfc4302#section-2) and [`Reserved` field description](https://www.rfc-editor.org/rfc/rfc4302#section-2.3).

Yes, I agree. It may become another protocol as we request for RISAV-AH, which ipsecme wg is disinclined. Just let's try to persuade them to modify the `Reserved` field.

But it also should deal with the `seq number` field carefully. Or we may keep the `seq num` field as 0 in RISAV. These are, of cause, some little details.
