### ISSUE TITLE
Publish v03

### ISSUE THREAD

**Issue by bemasc** [bemasc/draft-xu-risav#40]
I believe we may be ready to publish v03.  Are there any other issues that we should resolve before publishing a new revision?

**Comment by BasilGuo** [comment]
Agree.

The next question is where this draft should go. [ipsecme](https://datatracker.ietf.org/wg/ipsecme/about/), [secdispatch](https://datatracker.ietf.org/wg/secdispatch/about/), or both?

**Comment by bemasc** [comment]
I think we can keep IPSECME as the main group for now, but we should also try to get a few minutes to advertise the draft in 6MAN and SECDISPATCH.

**Comment by BasilGuo** [comment]
OK, would you please to publish v3? And I will ask these WGs for a agenda later.

**Comment by bemasc** [comment]
OK, I've triggered a publication.  You may need to click "approve" once you receive the notification email.

**Comment by BasilGuo** [comment]
Thanks a lot. It's very kind of you.

I have seen the tag [draft-xu-risav-03](https://github.com/bemasc/draft-xu-risav/tree/draft-xu-risav-03), but I don't know where to click the "approve" button for I don't receive such an email.

The datatracker page is not updated now or it just needs synchronization.

**Comment by BasilGuo** [comment]
It seems the job of "Publish New Draft Version" failed.

I'm sorry but you may need to adjust your email information as the process of "upload to datatracker" says `{"error": "No such user: ben@bemasc.net"}` at line 49.

![image](https://user-images.githubusercontent.com/42705918/223315201-3b66f182-19e2-4238-ac93-ea56fa8ebdd7.png)
![image](https://user-images.githubusercontent.com/42705918/223316407-fb41c6d4-0ddb-4383-b29b-90729565886f.png)

**Comment by bemasc** [comment]
Published as draft-xu-ipsecme-risav-00.
