### ISSUE TITLE
How do peers express a preference or requirement for transport or tunnel mode?

### ISSUE THREAD

**Issue by BasilGuo** [bemasc/draft-xu-risav#7]
**DESC**: This is proposed in Section Data Plane.
**OPEN QUESTION**: How do peers express a preference or requirement for transport or tunnel mode?

**Comment by bemasc** [comment]
I believe IKE is quite flexible and probably offers this capability (via USE_TRANSPORT_MODE), but I'm not quite sure how it works.  We need some advice from an IKE expert.
