### ISSUE TITLE
Do we need multiple contact IPs per AS, to support fragmented ASes?

### ISSUE THREAD

**Issue by BasilGuo** [bemasc/draft-xu-risav#8]
**DESC**: This is proposed together with #9 in Section Data Plane.
**OPEN QUESTION**: Do we need multiple contact IPs per AS, to support fragmented ASes?

**Comment by BasilGuo** [comment]
Single contact IP would suffer from Single Point Failure while Multiple contact IPs may lead to complexity in implementation. On another point, multiple contact IPs could shrink the IKE negotiation time but the collaboration of the IKE parties and the division of the IKE parties that one IKE node should keep in touch with are also complex tasks. In the long run, multiple contact IPs should be an important agenda for RISAV.
The full deployment of RISAV requires one deployer should keep in touch with almost all deployers which are a number of ASes, but a paper published at IMC15: [Are We One Hop Away from a Better Internet?](https://conferences2.sigcomm.org/imc/2015/papers/p523.pdf) shows that the average AS path to access Internet content is about 3.5 hops. Thus I think the IKE connection size should not be too large. So the multiple contact IPs may not be the first thing we should think about now. And I think a hierarchical structure of RISAV may be more useful for large-scale deployment but this may also cause larger complexity.

**Comment by bemasc** [comment]
> Single contact IP would suffer from Single Point Failure

I don't know that this is true.  I think the ACS can probably be implemented as a loosely-coupled anycast service.

The reason I think we might need multiple contact IPs is for ASes that have fragmented routing.  If a single AS is composed of several "islands" that have no route to each other, then each island would need its own contact IP.  However, I'm not familiar enough with BGP to understand if this is really allowed, or how common it is.

**Comment by BasilGuo** [comment]
As far as I know, this scenario (isolated routing area in one AS) is very rare. I recommend we could ignore this case at this time.

**Comment by bemasc** [comment]
OK, let's ignore that problem.  We can still support multiple contact IPs (i.e. multiple ACSes) within the current framework, so long as it is sufficient for a remote AS to contact any one of them.
